### PR TITLE
feat: basic layout and question bank page

### PR DESCRIPTION
**Pull request by TianqiCS**
### Check List
- [x] Fix #. (write the relative issue number)  
related: #33
- [x] Branch is up to date with master

- [x] Now it's a good time for reviewing

- [x] Branch should have prefix either "feature/" or "fix/"
feature: basic layout and question bank page
##### Comment

Put 'closes #.' in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by rw-moore — COMMENTED** [review]
Initial import of frontend code looks good...although I am a little worried about the tags which suggest the logo may spin every 20s! ;-)

**Review by rw-moore — APPROVED** [review]

**Comment by TianqiCS** [comment]
@rw-moore That's styles for the logo in the default page generated by the [CreateReactApp](https://facebook.github.io/create-react-app). So no worries.

**Comment by haotianzhu** [comment]
A branch should have prefix either "feature/" or "fix/" like feat/ frontend-init

**Comment by TianqiCS** [comment]
will be addressed in the next branch

**Pull request merged**
