### PR TITLE
Feat: tag model and its API

### PR DESCRIPTION
**Pull request by haotianzhu**
### Check List
- [x] Fix #. (write the relative issue number)

- [x] Branch is up to date with master

- [x] Now it's a good time for reviewing

- [x] Branch should have prefix either "feature/" or "fix/"

##### Comment

Put 'closes #.' in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by haotianzhu** [comment]
API: 
`GET /tags`
`POST /tags`
`PATCH /tags/:id`
` delete /tags/:id`
 `GET /tags/:id/questions`
Tag has a unique field name.
I keep id in case that you want to allow special characters for tag's name. 
The id is only for URL, you don't need to worry about id at request's body.

**Comment by haotianzhu** [comment]
For reviewing purpose:
This is the `TAG` model
```
class Tag(models.Model):
    '''
    name: the name of tag
    '''

    class Meta:
        app_label = 'polls'

    name = models.CharField(unique=True, max_length=20, null=False, blank=False)

    def __str__(self):
        return self.name

```

[API Part, click this](https://github.com/rw-moore/SciLO/blob/47394d9b67727801bc2619c0a08fc6302e94433e/polls/views/tag_views.py#L10-#L70)

**Comment by TianqiCS** [comment]
related: #26

**Review by TianqiCS — APPROVED** [review]

**Review by rw-moore — COMMENTED** [review]
Looks good based on a cursory inspection!

**Pull request merged**
